### ISSUE TITLE
Add GPL v3 license?

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo-icons#1]
Since we include those icons into Piwik released under GPLv3, could we release this repository under GPLv3 as well?

Tremendous job @Findus23 - you've made Piwik great again!

**Comment by Findus23** [comment]
Of course I can add the license.But how can I specify that only "my work" is under this license (so only the files in the root directory)?

**Comment by Findus23** [comment]
I solved this by not adding a LICENSE.md, but adding the GPL header to all my files and adding `misc/gpl-3.0.txt` from the piwik repository.
https://github.com/piwik/piwik-icons/commit/a834e80c6518b95395b5e55464ad2e17081524d4
