### ISSUE TITLE
Add icon for search engine search.avira.com

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo-icons#15]
As search engine definitions have been extended by `Avira SafeSearch` with url `search.avira.com`, we need to add an icon for it. Using the favicon should be fine I guess: https://search.avira.com/favicon.ico

@Findus23  Can you do that?

**Comment by Findus23** [comment]
Pay attention when updating the submodule, because I have already merged #14. Or should I revert it and move it to an branch until the main pull request is merged?

**Comment by sgiehl** [comment]
Guess is makes sense to revert and readd it as soon as main PR gets merged, so we can easily update the submodule

**Comment by Findus23** [comment]
Done in https://github.com/piwik/piwik-icons/commit/bbf7642bc1587c97952c706e67427cc388880db5
