### ISSUE TITLE
change color of all matomo Icons

### ISSUE THREAD

**Issue by ImenTurki** [matomo-org/matomo-icons#20]
I need to change the clors of all matomo icons, i update the calss at the navigator like this:
`[class^="icon-"], [class*=" icon-"] {
    font-family: 'matomo' !important;
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    color: #ff66054;
}`

but i did succed to do change on the server ,  any idea ?

**Comment by Findus23** [comment]
Hi,

This is the repository that collects png images for browsers and other things that are used in Matomo. Please ask questions about Matomo on the forum.

That said the CSS you posted works for me (when e.g. changing color to orange)
![grafik](https://user-images.githubusercontent.com/6266037/66660193-10c8bb80-ec45-11e9-9baf-22caa277388d.png)
