### ISSUE TITLE
Missing icon for wearable devices

### ISSUE THREAD

**Issue by ufoproger** [matomo-org/matomo-icons#23]
I am using latest Matomo release 3.14.1. If you look at the block with device types, wearable devices are shown with a broken icon. 
Image element markup: `<img title="Wearable" alt="Wearable" src="plugins/Morpheus/icons/dist/devices/wearable.png">`.

![Missing wearable icon](https://user-images.githubusercontent.com/212711/93169341-19781a80-f74f-11ea-8759-755861be5c64.png)

**Comment by Findus23** [comment]
Hi,

The device type has been added in https://github.com/matomo-org/device-detector/pull/6217 and I seem to have missed it.

I have now added the icon in 7e8778b
