### ISSUE TITLE
sources of browser logos, information about browsers

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/matomo-icons#24]
I suggest pointing out useful resources in this issue

https://browserss.ru/logotipy_brauzerov.php 
there are a lot of browser logos, and the site also has information about browsers. the website is unfortunately only in Russian

**Comment by Findus23** [comment]
Browser logos is less of an issue as there is https://github.com/alrra/browser-logos which contains high resolution logos for many of them. The selection of browsers there makes me think that the website even uses this repo as the source for most logos.

Nevertheless thanks for the pointer.
