### ISSUE TITLE
Update Mac icon to latest version of Finder

### ISSUE THREAD

**Issue by Studio384** [matomo-org/matomo-icons#5]
The Finder icon in Piwik doesn't match the official logo: https://upload.wikimedia.org/wikipedia/en/4/45/Mac_Finder_icon_%28OS_X_Yosemite%29.png

**Comment by Findus23** [comment]
Thanks for the report.

I used this icon as the mac OS text logo isn't readable if it's too small. I didn't know this was the icon of Finder and that there is a newer logo. 

I'll replace it if I have some time.
