### ISSUE TITLE
Opera Mini, Opera Beta and Opera/Opera Mobile icons all have slightly different dimensions

### ISSUE THREAD

**Issue by Studio384** [matomo-org/matomo-icons#6]
The Opera icons in this repository are all slightly different in the way they are sized. On the scale these icons are showed, it is quiet visible:

Mini: https://github.com/piwik/piwik-icons/blob/master/dist/browsers/OI.png
Opera (Mobile): https://github.com/piwik/piwik-icons/blob/master/dist/browsers/OM.png
Opera Beta: https://github.com/piwik/piwik-icons/blob/master/dist/browsers/ON.png

Also, the Opera/Opera Mobile icon doesn't seem to be the official icon as the shade on the right starts to low and is to sudden.

Additionally, is the Opera Developer logo not used by Piwik?

**Comment by Findus23** [comment]
> The Opera icons in this repository are all slightly different in the way they are sized

You are right, this is unfortunately a side effect of trimming all icons before resizing, as the "mini"-Patch is outstanding on the right side.

> Also, the Opera/Opera Mobile icon doesn't seem to be the official icon as the shade on the right starts to low and is to sudden.

As you can see in https://github.com/piwik/piwik-icons/blob/master/src/browsers/OP.png.source I am using the image from here https://commons.wikimedia.org/wiki/File:Opera_2015_icon.svg
which quotes http://www.operasoftware.com/press/resources/logos as a source. 

> Additionally, is the Opera Developer logo not used by Piwik?

I am only adding icons for browsers device-detector is able to detect.
(which is the following list: https://github.com/piwik/device-detector/blob/master/Parser/Client/Browser.php#L29)

If you want to add Opera Developer you'll need to open an issue with the user agent there.

**Comment by Studio384** [comment]
Well the default Opera icon and Opera Beta are also different in size, trimming shouldn't affect that. Perhaps it's best to not trim them all the way to the edge of the icons but instead to the lowest possible trim of any of the icons - which would be Mini - and go from there to make sure there is consistency between these icons.

**Comment by Findus23** [comment]
The difference between the standard opera icon and the opera beta icon is that the first is a high resolution image with a sharp border, while the beta icon is quite blurry and has a slight shadow on the right side. Because of this the trim includes this shadow as one row of pixels on the right side.

The best solution would be a better source file for opera beta. (Maybe from #4)

**Comment by Findus23** [comment]
@Studio384, can you test the icons here, if they are better: #7

**Comment by Studio384** [comment]
I'll try this Sunday, I don't have time before then, sorry.

**Comment by Findus23** [comment]
@Studio384 Did you have time to look into this again? (And maybe also the new brand icons)

**Comment by Findus23** [comment]
If you are still having issues with the opera icons, please reopen the issue.
